In [1]:
!jt -t onedork -fs 12 -cellw 95%

import os
import pandas as pd
import folium

from folium.features import DivIcon

In [38]:
pd.set_option('display.max.columns', 50)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

# Data 탐색

## berth_df: 정계지 위치 정보
### 정계지란, 도선사들이 대기하는 위치

In [2]:
berth_df = pd.read_csv("정계지 위치.csv")

In [5]:
lat, lon = berth_df["위도"].mean(), berth_df["경도"].mean()
map_obj = folium.Map(location=[lat, lon], zoom_start=13)

# CircleMarker 내부에 텍스트 표시
for _, _val in berth_df.iterrows():
    _lat, _lon = _val["위도"], _val["경도"]
    _name = _val["정계지"][:2]
    
    folium.CircleMarker(
        location=[_lat, _lon],
        radius=30,
        color="",
        fill=True,
        fill_color="#ff7800",
        fill_opacity=0.3
    ).add_to(map_obj)
    
    folium.map.Marker(
        [_lat, _lon],
        icon=DivIcon(
            icon_size=(60, 20),  # 아이콘 크기 조정
            icon_anchor=(30, 10),  # 앵커 위치 조정
            html=f'<div style="font-size: 8pt; color : black; text-align: center; font-weight: bold;">{_name}</div>',
        )
    ).add_to(map_obj)

In [6]:
map_obj

주어진 예선데이터를 기반으로 간단한 Toy Problem을 풀어보고자 함

> 데이터 전처리를 진행해보고, 원하는 형태의 df를 제안할 예정

In [ ]:
df = pd.read_excel("예선데이터_인천항.xlsx")

In [40]:
df.columns.tolist()

['기준예선',
 '배정예선',
 '선박명',
 'From',
 '작업 시작지',
 '작업 종료지',
 'To',
 '실제 스케줄 시작 시각',
 '실제 스케줄 종료 시각',
 '작업까지 이동 거리(km)',
 '작업까지 이동 시간(분)',
 '작업중 이동 거리(km)',
 '작업중 이동 시간(분)',
 '도선사',
 '톤수',
 '선종',
 '최종 스케줄 시각',
 '최초 스케줄 시각',
 '최초 작업시작지',
 '최초 작업종료지',
 '최초 예선',
 '최초 도선사',
 'AIS 파일명 target',
 'AIS 파일명 tug']

In [ ]:
col_oi = []

In [44]:
df.head()

  기준예선  배정예선                선박명     From 작업 시작지 작업 종료지       To              실제 스케줄 시작 시각              실제 스케줄 종료 시각  작업까지 이동 거리(km)  작업까지 이동 시간(분)  작업중 이동 거리(km)  작업중 이동 시간(분) 도선사     톤수       선종                 최종 스케줄 시각                 최초 스케줄 시각 최초 작업시작지 최초 작업종료지 최초 예선 최초 도선사                                          AIS 파일명 target                                          AIS 파일명 tug
0    I   성,I          REVERENCE      NaN   NPPS  SNCT2    송도정계지  2024-06-08T07:32:18.000Z  2024-06-08T08:15:18.000Z           8.571      30.000000          4.909     38.000000  KU   9990   풀컨테이너선  2024-06-08T07:00:00.000Z  2024-06-08T07:00:00.000Z     NPPS    SNCT2    성I     KU         쥬피터1호_REVERENCE_2024-06-08_target_1_aisData.csv         쥬피터1호_REVERENCE_2024-06-08_tug_1_aisData.csv
1    M  F1,M     SEAWAYS MOMENT      NaN  SKI 2   DONG      NaN  2024-06-08T07:10:18.000Z  2024-06-08T07:20:18.000Z           0.626       2.000000          1.859      5.000000  JJ  29293  케미칼 운반선  2024-06-08T07:00:00.000Z  2024-06-08T07:00:00.000Z    SKI 2     DONG   F1M     JJ     뉴마스호_SEAWAYS MOMENT_2024-06-08_target_2_aisData.csv     뉴마스호_SEAWAYS MOMENT_2024-06-08_tug_2_aisData.csv
2    T   T,S    YURIY TARAPUROV  연안부두정계지    PAL    N53      NaN  2024-06-08T10:51:18.000Z  2024-06-08T11:01:19.000Z           5.673      25.983333          2.561     35.016667  CY   7949    일반화물선  2024-06-08T09:20:00.000Z  2024-06-08T09:00:00.000Z      PAL      N53    TS     CY     대창호_YURIY TARAPUROV_2024-06-08_target_3_aisData.csv     대창호_YURIY TARAPUROV_2024-06-08_tug_3_aisData.csv
3    M     M            BIRYONG  연안부두정계지    PAL  NIPT2      NaN  2024-06-08T10:26:18.000Z  2024-06-08T11:01:18.000Z           5.235      47.000000          3.371     30.000000  KI  14614    국제카페리  2024-06-08T09:50:00.000Z  2024-06-08T09:30:00.000Z      PAL    NIPT2     M     KI            뉴마스호_BIRYONG_2024-06-08_target_4_aisData.csv            뉴마스호_BIRYONG_2024-06-08_tug_4_aisData.csv
4    M     M  XIN XIANG XUE LAN      NaN    PAL  NIPT5  연안부두정계지  2024-06-08T11:20:18.000Z  2024-06-08T11:59:18.000Z           4.024      26.983333          4.567     34.000000  JJ  32729    국제카페리  2024-06-08T10:50:00.000Z  2024-06-08T10:30:00.000Z      PAL    NIPT5     M    NaN  뉴마스호_XIN XIANG XUE LAN_2024-06-08_target_5_aisData.csv  뉴마스호_XIN XIANG XUE LAN_2024-06-08_tug_5_aisData.csv

In [39]:
df

    기준예선               배정예선                  선박명     From  작업 시작지  작업 종료지       To              실제 스케줄 시작 시각              실제 스케줄 종료 시각  작업까지 이동 거리(km)  작업까지 이동 시간(분)  작업중 이동 거리(km)  작업중 이동 시간(분)  도선사      톤수                                 선종                 최종 스케줄 시각                 최초 스케줄 시각 최초 작업시작지 최초 작업종료지       최초 예선 최초 도선사                                               AIS 파일명 target                                               AIS 파일명 tug
0      I                성,I            REVERENCE      NaN    NPPS   SNCT2    송도정계지  2024-06-08T07:32:18.000Z  2024-06-08T08:15:18.000Z           8.571      30.000000          4.909     38.000000   KU    9990                             풀컨테이너선  2024-06-08T07:00:00.000Z  2024-06-08T07:00:00.000Z     NPPS    SNCT2          성I     KU              쥬피터1호_REVERENCE_2024-06-08_target_1_aisData.csv              쥬피터1호_REVERENCE_2024-06-08_tug_1_aisData.csv
1      M               F1,M       SEAWAYS MOMENT      NaN   SKI 2    DONG      NaN  2024-06-08T07:10:18.000Z  2024-06-08T07:20:18.000Z           0.626       2.000000          1.859      5.000000   JJ   29293                            케미칼 운반선  2024-06-08T07:00:00.000Z  2024-06-08T07:00:00.000Z    SKI 2     DONG         F1M     JJ          뉴마스호_SEAWAYS MOMENT_2024-06-08_target_2_aisData.csv          뉴마스호_SEAWAYS MOMENT_2024-06-08_tug_2_aisData.csv
2      T                T,S      YURIY TARAPUROV  연안부두정계지     PAL     N53      NaN  2024-06-08T10:51:18.000Z  2024-06-08T11:01:19.000Z           5.673      25.983333          2.561     35.016667   CY    7949                              일반화물선  2024-06-08T09:20:00.000Z  2024-06-08T09:00:00.000Z      PAL      N53          TS     CY          대창호_YURIY TARAPUROV_2024-06-08_target_3_aisData.csv          대창호_YURIY TARAPUROV_2024-06-08_tug_3_aisData.csv
3      M                  M              BIRYONG  연안부두정계지     PAL   NIPT2      NaN  2024-06-08T10:26:18.000Z  2024-06-08T11:01:18.000Z           5.235      47.000000          3.371     30.000000   KI   14614                              국제카페리  2024-06-08T09:50:00.000Z  2024-06-08T09:30:00.000Z      PAL    NIPT2           M     KI                 뉴마스호_BIRYONG_2024-06-08_target_4_aisData.csv                 뉴마스호_BIRYONG_2024-06-08_tug_4_aisData.csv
4      M                  M    XIN XIANG XUE LAN      NaN     PAL   NIPT5  연안부두정계지  2024-06-08T11:20:18.000Z  2024-06-08T11:59:18.000Z           4.024      26.983333          4.567     34.000000   JJ   32729                              국제카페리  2024-06-08T10:50:00.000Z  2024-06-08T10:30:00.000Z      PAL    NIPT5           M    NaN       뉴마스호_XIN XIANG XUE LAN_2024-06-08_target_5_aisData.csv       뉴마스호_XIN XIANG XUE LAN_2024-06-08_tug_5_aisData.csv
5      N                N,O        SEONGHO PIOCE  연안부두정계지     PAL   SKI 2  북항임시정계지  2024-06-08T15:02:19.000Z  2024-06-08T15:43:19.000Z           7.567      30.000000          2.935     36.000000   KK    3698                           석유제품 운반선  2024-06-08T14:10:00.000Z  2024-06-08T14:00:00.000Z      PAL    SKI 2          NO    NaN           뉴엔젤호_SEONGHO PIOCE_2024-06-08_target_6_aisData.csv           뉴엔젤호_SEONGHO PIOCE_2024-06-08_tug_6_aisData.csv
6      T                R,T        QUEZON BRIDGE  연안부두정계지     PAL    ICT1  연안부두정계지  2024-06-08T15:03:19.000Z  2024-06-08T15:44:19.000Z           6.435      36.000000          3.391     36.000000   LY   17211                             풀컨테이너선  2024-06-08T14:20:00.000Z  2024-06-08T14:30:00.000Z      PAL     ICT1          RT    NaN            대창호_QUEZON BRIDGE_2024-06-08_target_7_aisData.csv            대창호_QUEZON BRIDGE_2024-06-08_tug_7_aisData.csv
7      I                K,I    KMTC LAEM CHABANG    송도정계지    NPPS   HJIT3    송도정계지  2024-06-09T06:53:19.000Z  2024-06-09T07:43:19.000Z           2.364      17.000000          6.017     45.000000   RW   18318                             풀컨테이너선  2024-06-09T06:30:00.000Z  2024-06-09T06:30:00.000Z     NPPS    HJIT3          KI     RW      쥬피터1호_KMTC LAEM CHABANG_2024-06-09_target_8_aisData.csv      쥬피터1호_KMTC LAEM CHABANG_2024-06-09_tug_8_aisData.csv
8      명         L,F2,B,비,명            GOOD LUCK    내항정계지     LEN      43    내항정계지  2024-06-09T08:13:19.000Z  2024-06-09T09:10:19.000Z           1.213       8.000000          3.173     52.000000   JH   41074                           산물선(벌크선)  2024-06-09T06:30:00.000Z  2024-06-09T06:30:00.000Z      LEN       43      LF2B비명     JH                대명호_GOOD LUCK_2024-06-09_target_9_aisData.csv                대명호_GOOD LUCK_2024-06-09_tug_9_aisData.csv
9      N                N,Q            WOO CHOON  북항임시정계지     GSD     PAL      NaN  2024-06-09T09:45:19.000Z  2024-06-09T10:07:19.000Z           4.850      24.000000          1.422     17.000000  NaN    3969                           석유제품 운반선  2024-06-09T10:00:00.000Z  2024-06-09T10:00:00.000Z      GSD      PAL          NQ    NaN              뉴엔젤호_WOO CHOON_2024-06-09_target_10_aisData.csv              뉴엔젤호_WOO CHOON_2024-06-09_tug_10_aisData.csv
10     T            T,R,해,진        SILVER SAFETY  연안부두정계지     PAL      50  연안부두정계지  2024-06-09T10:37:19.000Z  2024-06-09T11:22:19.000Z           2.471      19.000000          4.830     40.000000   US    7243                              일반화물선  2024-06-09T09:30:00.000Z  2024-06-09T10:00:00.000Z      PAL       50        TR해진    NaN           대창호_SILVER SAFETY_2024-06-09_target_11_aisData.csv           대창호_SILVER SAFETY_2024-06-09_tug_11_aisData.csv
11     I                I,성     XIN MING ZHOU 20    송도정계지    NPPS   SNCT1      NaN  2024-06-09T12:31:19.000Z  2024-06-09T12:41:19.000Z           5.595      21.000000          1.286     18.000000   CY    9653                             풀컨테이너선  2024-06-09T12:00:00.000Z  2024-06-09T12:00:00.000Z     NPPS    SNCT1          I성    NaN      쥬피터1호_XIN MING ZHOU 20_2024-06-09_target_12_aisData.csv      쥬피터1호_XIN MING ZHOU 20_2024-06-09_tug_12_aisData.csv
12     H                  H         GSL DOROTHEA  연안부두정계지   HJIT2    NPPS      NaN  2024-06-09T15:56:19.000Z  2024-06-09T16:33:19.000Z          20.348      59.000000          0.520     32.000000   JJ   66058                             풀컨테이너선  2024-06-09T16:30:00.000Z  2024-06-09T15:00:00.000Z    HJIT2     NPPS           H    NaN           한창1호_GSL DOROTHEA_2024-06-09_target_13_aisData.csv           한창1호_GSL DOROTHEA_2024-06-09_tug_13_aisData.csv
13     미                미,O             UNIPOWER  연안부두정계지     N12     PAL  연안부두정계지  2024-06-09T16:20:18.000Z  2024-06-09T16:51:18.000Z           5.650     801.016667          0.580     26.000000   KK    8081                              일반화물선  2024-06-09T16:40:00.000Z  2024-06-09T18:00:00.000Z      N12      PAL          미O    NaN               뉴월미호_UNIPOWER_2024-06-09_target_14_aisData.csv               뉴월미호_UNIPOWER_2024-06-09_tug_14_aisData.csv
14     M            M,R,해,진            VW SAFETY  연안부두정계지     PAL      50  연안부두정계지  2024-06-10T06:41:19.000Z  2024-06-10T07:25:19.000Z           2.135       9.000000          5.107     39.000000   CH    7141                              일반화물선  2024-06-10T06:00:00.000Z  2024-06-10T06:00:00.000Z      PAL       50        MR해진     CH              뉴마스호_VW SAFETY_2024-06-10_target_15_aisData.csv              뉴마스호_VW SAFETY_2024-06-10_tug_15_aisData.csv
15     진                T,진    XIN SHENG SHENG 6      NaN     PAL      42      NaN  2024-06-10T07:45:20.000Z  2024-06-10T08:31:20.000Z           1.525      13.016667          2.939     41.000000   CY    2995                              일반화물선  2024-06-10T06:00:00.000Z  2024-06-10T06:00:00.000Z      PAL       42          T진     CY      뉴약진호_XIN SHENG SHENG 6_2024-06-10_target_16_aisData.csv      뉴약진호_XIN SHENG SHENG 6_2024-06-10_tug_16_aisData.csv
16     N                N,O            OCEAN GAS  연안부두정계지   SKI 1     PAL  연안부두정계지  2024-06-10T08:50:20.000Z  2024-06-10T09:10:20.000Z           9.110      36.000000          3.182     15.000000  NaN    3678                            LPG 운반선  2024-06-10T09:00:00.000Z  2024-06-10T07:00:00.000Z    SKI 1      PAL          NO    NaN              뉴엔젤호_OCEAN GAS_2024-06-10_target_17_aisData.csv              뉴엔젤호_OCEAN GAS_2024-06-10_tug_17_aisData.csv
17     H                  H      HUADONG PEARL 8  연안부두정계지     PAL   NIPT5      NaN  2024-06-10T09:48:19.000Z  2024-06-10T10:23:19.000Z           3.997      18.000000          0.830     10.000000   LY   35092                              국제카페리  2024-06-10T09:10:00.000Z  2024-06-10T09:30:00.000Z      PAL    NIPT5           H    NaN        한창1호_HUADONG PEARL 8_2024-06-10_target_18_aisData.csv        한창1호_HUADONG PEARL 8_2024-06-10_tug_18_aisData.csv
18     I                  I          CONSISTENCE    송도정계지   HJIT1    NPPS      NaN  2024-06-10T10:28:19.000Z  2024-06-10T11:16:19.000Z           8.528     180.000000          0.000     43.000000   UM    9972                             풀컨테이너선  2024-06-10T11:00:00.000Z  2024-06-10T10:00:00.000Z    HJIT1     NPPS           I    NaN           쥬피터1호_CONSISTENCE_2024-06-10_target_19_aisData.csv           쥬피터1호_CONSISTENCE_2024-06-10_tug_19_aisData.csv
19     I                I,성              A ROKKO      NaN    NPPS   HJIT1      NaN  2024-06-10T12:36:19.000Z  2024-06-10T12:49:19.000Z           3.328     167.000000          0.000      8.000000   OS    9562                             풀컨테이너선  2024-06-10T12:00:00.000Z  2024-06-10T12:00:00.000Z     NPPS    HJIT1          I성    NaN               쥬피터1호_A ROKKO_2024-06-10_target_20_aisData.csv               쥬피터1호_A ROKKO_2024-06-10_tug_20_aisData.csv
20     I                I,K            XIN HE DA      NaN   HJIT1    NPPS      NaN  2024-06-10T11:12:19.000Z  2024-06-10T12:34:19.000Z           0.000       2.000000          0.115     77.000000   GJ    7808                        세미(혼재)컨테이너선  2024-06-10T15:00:00.000Z  2024-06-10T15:00:00.000Z    HJIT1     NPPS          IK    NaN             쥬피터1호_XIN HE DA_2024-06-10_target_21_aisData.csv             쥬피터1호_XIN HE DA_2024-06-10_tug_21_aisData.csv
21     I                I,K         KOREA VISION      NaN   BUKJ2    E1GT      NaN  2024-06-10T15:24:19.000Z  2024-06-10T16:13:19.000Z           4.450     191.000000          1.727     44.000000   KB    3872                            LPG 운반선  2024-06-10T15:00:00.000Z  2024-06-10T15:00:00.000Z    BUKJ2     E1GT          IK    NaN          쥬피터1호_KOREA VISION_2024-06-10_target_22_aisData.csv          쥬피터1호_KOREA VISION_2024-06-10_tug_22_aisData.csv
22     I                  I        PEGASUS PROTO      NaN    NPPS   SNCT1      NaN  2024-06-10T16:43:19.000Z  2024-06-10T16:58:19.000Z           5.378     205.000000          0.079     10.000000  NaN   18354                             풀컨테이너선  2024-06-10T16:30:00.000Z  2024-06-10T17:00:00.000Z     NPPS    SNCT1           I    NaN         쥬피터1호_PEGASUS PROTO_2024-06-10_target_23_aisData.csv         쥬피터1호_PEGASUS PROTO_2024-06-10_tug_23_aisData.csv
23     N                성,N           AN DONG 68  연안부두정계지   SNCT2    NPPS      NaN  2024-06-10T16:49:20.000Z  2024-06-10T17:06:20.000Z          20.926     122.000000          0.120      5.000000   HY    3988                        세미(혼재)컨테이너선  2024-06-10T16:00:00.000Z  2024-06-10T07:00:00.000Z     NPPS    SNCT2          I성     JJ             뉴엔젤호_AN DONG 68_2024-06-10_target_24_aisData.csv             뉴엔젤호_AN DONG 68_2024-06-10_tug_24_aisData.csv
24     미                W,미      YURIY TARAPUROV  북항임시정계지     N53     PAL  연안부두정계지  2024-06-10T16:06:19.000Z  2024-06-10T16:54:19.000Z           1.801      11.000000          6.093     43.000000   YM    7949                              일반화물선  2024-06-10T16:30:00.000Z  2024-06-10T17:00:00.000Z      N53      PAL          EN    NaN        뉴월미호_YURIY TARAPUROV_2024-06-10_target_25_aisData.csv        뉴월미호_YURIY TARAPUROV_2024-06-10_tug_25_aisData.csv
25     N              W,N,진    XINXIWANGMINGYUAN      NaN     N11      25      NaN  2024-06-10T18:03:20.000Z  2024-06-10T18:42:20.000Z          21.187      80.000000          4.665     34.000000   SK    2589                              일반화물선  2024-06-10T18:00:00.000Z  2024-06-10T18:00:00.000Z      N11       25         SN진    NaN      뉴엔젤호_XINXIWANGMINGYUAN_2024-06-10_target_26_aisData.csv      뉴엔젤호_XINXIWANGMINGYUAN_2024-06-10_tug_26_aisData.csv
26     I                성,I               ESTIMA      NaN    NPPS   HJIT1      NaN  2024-06-10T19:47:19.000Z  2024-06-10T20:05:19.000Z           6.836     482.016667          0.862     13.000000   LO    9587                             풀컨테이너선  2024-06-10T19:00:00.000Z  2024-06-10T20:00:00.000Z     NPPS    HJIT1          성I    NaN                쥬피터1호_ESTIMA_2024-06-10_target_27_aisData.csv                쥬피터1호_ESTIMA_2024-06-10_tug_27_aisData.csv
27     M                W,M    ORIENTAL PARALLEL  연안부두정계지     N42     PAL  연안부두정계지  2024-06-10T19:53:19.000Z  2024-06-10T20:17:19.000Z          14.612      44.000000          2.451     19.000000   GJ    9780                              일반화물선  2024-06-10T20:00:00.000Z  2024-06-10T23:00:00.000Z      N42      PAL          W미    NaN      뉴마스호_ORIENTAL PARALLEL_2024-06-10_target_28_aisData.csv      뉴마스호_ORIENTAL PARALLEL_2024-06-10_tug_28_aisData.csv
28     미                E,미     XIN YU JIN XIANG  연안부두정계지   NIPT6     PAL  연안부두정계지  2024-06-11T00:16:19.000Z  2024-06-11T00:48:19.000Z           6.114      22.000000          3.612     27.000000   KB   12304                              국제카페리  2024-06-11T00:30:00.000Z  2024-06-11T00:30:00.000Z    NIPT6      PAL          E미     KB       뉴월미호_XIN YU JIN XIANG_2024-06-11_target_29_aisData.csv       뉴월미호_XIN YU JIN XIANG_2024-06-11_tug_29_aisData.csv
29     N                  N             DB SUNNY  연안부두정계지      W4     HIT  연안부두정계지  2024-06-11T06:27:20.000Z  2024-06-11T07:02:20.000Z           7.074      58.000000          3.014     30.000000  NaN    1599                            케미칼 운반선  2024-06-11T06:00:00.000Z  2024-06-11T06:00:00.000Z       W4      HIT           N    NaN               뉴엔젤호_DB SUNNY_2024-06-11_target_30_aisData.csv               뉴엔젤호_DB SUNNY_2024-06-11_tug_30_aisData.csv
30     I                I,성         KOREA VISION      NaN    E1GT   BUKJ2    송도정계지  2024-06-11T07:02:19.000Z  2024-06-11T07:15:19.000Z           2.526     246.983333          0.072      8.000000   NS    3872                            LPG 운반선  2024-06-11T07:00:00.000Z  2024-06-11T07:00:00.000Z     E1GT    BUKJ2          I성     NS          쥬피터1호_KOREA VISION_2024-06-11_target_31_aisData.csv          쥬피터1호_KOREA VISION_2024-06-11_tug_31_aisData.csv
31     미                E,미            BEI JIANG  연안부두정계지     PAL    KICT  연안부두정계지  2024-06-11T08:05:19.000Z  2024-06-11T08:34:19.000Z          24.046      91.000000          2.940     24.000000   SC    5250                              일반화물선  2024-06-11T07:00:00.000Z  2024-06-11T07:00:00.000Z      PAL     KICT          E미     SC              뉴월미호_BEI JIANG_2024-06-11_target_32_aisData.csv              뉴월미호_BEI JIANG_2024-06-11_tug_32_aisData.csv
32     진                윤,진            VW SAFETY    내항정계지      50     PAL    내항정계지  2024-06-11T06:45:20.000Z  2024-06-11T07:11:20.000Z           2.825      21.000000          1.114     21.000000   LO    7141                              일반화물선  2024-06-11T07:00:00.000Z  2024-06-11T07:00:00.000Z       50      PAL          윤진     LO              뉴약진호_VW SAFETY_2024-06-11_target_33_aisData.csv              뉴약진호_VW SAFETY_2024-06-11_tug_33_aisData.csv
33     T                T,G         ARAFURA LILY  연안부두정계지     PAL   NIPT6  연안부두정계지  2024-06-11T06:52:20.000Z  2024-06-11T07:20:20.000Z           7.418      35.000000          2.240     23.000000   CG   12335                              국제카페리  2024-06-11T06:30:00.000Z  2024-06-11T06:30:00.000Z      PAL    NIPT6          TG     SK            대창호_ARAFURA LILY_2024-06-11_target_34_aisData.csv            대창호_ARAFURA LILY_2024-06-11_tug_34_aisData.csv
34     T                  T    XIN XIANG XUE LAN  연안부두정계지     PAL   NIPT5      NaN  2024-06-11T11:35:20.000Z  2024-06-11T11:45:20.000Z           3.955      17.000000          2.995     33.000000   GH   32729                              국제카페리  2024-06-11T10:20:00.000Z  2024-06-11T10:30:00.000Z      PAL    NIPT5           T    NaN       대창호_XIN XIANG XUE LAN_2024-06-11_target_35_aisData.csv       대창호_XIN XIANG XUE LAN_2024-06-11_tug_35_aisData.csv
35     I                L,I          WAN HAI 317    송도정계지    NPPS   SNCT1    송도정계지  2024-06-11T12:32:20.000Z  2024-06-11T15:49:20.000Z           5.377      21.000000          5.793    192.000000   NS   27800                             풀컨테이너선  2024-06-11T12:00:00.000Z  2024-06-11T12:00:00.000Z     NPPS    SNCT1          LI    NaN           쥬피터1호_WAN HAI 317_2024-06-11_target_36_aisData.csv           쥬피터1호_WAN HAI 317_2024-06-11_tug_36_aisData.csv
36     진                  진    XIN SHENG SHENG 6    내항정계지      42     PAL      NaN  2024-06-11T15:39:20.000Z  2024-06-11T16:14:20.000Z           1.961      12.000000          3.198     30.000000   SC    2995                              일반화물선  2024-06-11T16:00:00.000Z  2024-06-11T16:00:00.000Z       42      PAL           진    NaN      뉴약진호_XIN SHENG SHENG 6_2024-06-11_target_37_aisData.csv      뉴약진호_XIN SHENG SHENG 6_2024-06-11_tug_37_aisData.csv
37     T                T,R         ARAFURA LILY  연안부두정계지   NIPT6     PAL      NaN  2024-06-11T16:31:20.000Z  2024-06-11T16:41:20.000Z           4.937      21.000000          3.041     21.000000   KB   12335                              국제카페리  2024-06-11T16:30:00.000Z  2024-06-11T06:30:00.000Z      PAL    NIPT6          TG     SK            대창호_ARAFURA LILY_2024-06-11_target_38_aisData.csv            대창호_ARAFURA LILY_2024-06-11_tug_38_aisData.csv
38     동              비,명,동      MANHASSET QUEEN      NaN      73     PAL      NaN  2024-06-11T17:33:20.000Z  2024-06-11T18:33:20.000Z           1.515      17.000000          0.142      8.000000   SK   36139                           산물선(벌크선)  2024-06-11T18:00:00.000Z  2024-06-11T18:00:00.000Z       73      PAL         비명동    NaN        동보1호_MANHASSET QUEEN_2024-06-11_target_39_aisData.csv        동보1호_MANHASSET QUEEN_2024-06-11_tug_39_aisData.csv
39     진                해,진            SUN OCEAN    내항정계지      30      LE    내항정계지  2024-06-11T22:58:20.000Z  2024-06-11T23:45:20.000Z           2.203      11.000000          3.762     42.000000   YM    5093                              일반화물선  2024-06-11T23:30:00.000Z  2024-06-11T23:30:00.000Z       30       LE          해진    NaN              뉴약진호_SUN OCEAN_2024-06-11_target_40_aisData.csv              뉴약진호_SUN OCEAN_2024-06-11_tug_40_aisData.csv
40     미                미,R             FC DELLA  연안부두정계지   N-HOB     PAL  북항임시정계지  2024-06-11T21:15:19.000Z  2024-06-11T21:49:19.000Z           7.206      27.000000          3.544     29.000000  NaN    4956                            케미칼 운반선  2024-06-11T21:30:00.000Z  2024-06-11T12:00:00.000Z      PAL    N-HOB          OS    NaN               뉴월미호_FC DELLA_2024-06-11_target_41_aisData.csv               뉴월미호_FC DELLA_2024-06-11_tug_41_aisData.csv
41     동                동,진        SILVER SAFETY    내항정계지      50     PAL      NaN  2024-06-11T21:00:20.000Z  2024-06-11T21:35:20.000Z           2.623      12.000000          0.838     27.000000   KU    7243                              일반화물선  2024-06-11T21:30:00.000Z  2024-06-11T14:00:00.000Z       50      PAL          해진    NaN          동보1호_SILVER SAFETY_2024-06-11_target_42_aisData.csv          동보1호_SILVER SAFETY_2024-06-11_tug_42_aisData.csv
42     N                N,E         HONG YANG 28  연안부두정계지     PAL    E1CT  연안부두정계지  2024-06-12T02:40:20.000Z  2024-06-12T03:27:20.000Z           5.698     161.983333          4.471     42.016667   SK   11856                             풀컨테이너선  2024-06-12T02:00:00.000Z  2024-06-12T02:00:00.000Z      PAL     E1CT          NE     SK           뉴엔젤호_HONG YANG 28_2024-06-12_target_43_aisData.csv           뉴엔젤호_HONG YANG 28_2024-06-12_tug_43_aisData.csv

In [32]:
df["From"].unique()

array([nan, '연안부두정계지', '송도정계지', '내항정계지', '북항임시정계지'], dtype=object)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   기준예선            336 non-null    object
 1   배정예선            336 non-null    object
 2   선박명             336 non-null    object
 3   From            217 non-null    object
 4   작업 시작지          336 non-null    object
 5   작업 종료지          336 non-null    object
 6   To              190 non-null    object
 7   실제 스케줄 시작 시각    336 non-null    object
 8   실제 스케줄 종료 시각    336 non-null    object
 9   작업까지 이동 거리(km)  336 non-null    float64
 10  작업까지 이동 시간(분)   336 non-null    float64
 11  작업중 이동 거리(km)   336 non-null    float64
 12  작업중 이동 시간(분)    336 non-null    float64
 13  도선사             252 non-null    object
 14  톤수              336 non-null    int64
 15  선종              336 non-null    object
 16  최종 스케줄 시각       336 non-null    object
 17  최초 스케줄 시각       336 non-null    object
 18  최초 작업시작지        336 non-null    object
 19  최초 작업종료지        336 non-null    object
 20  최초 예선           336 non-null    object
 21  최초 도선사          104 non-null    object
 22  AIS 파일명 target  336 non-null    object
 23  AIS 파일명 tug     336 non-null    object
dtypes: float64(4), int64(1), object(19)
memory usage: 63.1+ KB

In [28]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, 7 to 317
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   기준예선            48 non-null     object
 1   배정예선            48 non-null     object
 2   선박명             48 non-null     object
 3   From            48 non-null     object
 4   작업 시작지          48 non-null     object
 5   작업 종료지          48 non-null     object
 6   To              48 non-null     object
 7   실제 스케줄 시작 시각    48 non-null     object
 8   실제 스케줄 종료 시각    48 non-null     object
 9   작업까지 이동 거리(km)  48 non-null     float64
 10  작업까지 이동 시간(분)   48 non-null     float64
 11  작업중 이동 거리(km)   48 non-null     float64
 12  작업중 이동 시간(분)    48 non-null     float64
 13  도선사             48 non-null     object
 14  톤수              48 non-null     int64
 15  선종              48 non-null     object
 16  최종 스케줄 시각       48 non-null     object
 17  최초 스케줄 시각       48 non-null     object
 18  최초 작업시작지        48 non-null     object
 19  최초 작업종료지        48 non-null     object
 20  최초 예선           48 non-null     object
 21  최초 도선사          48 non-null     object
 22  AIS 파일명 target  48 non-null     object
 23  AIS 파일명 tug     48 non-null     object
dtypes: float64(4), int64(1), object(19)
memory usage: 9.4+ KB

In [24]:
type(df.From.iloc[0])

float

In [10]:
df = pd.read_excel("예선데이터_인천항.xlsx")

In [12]:
df.columns

Index(['기준예선', '배정예선', '선박명', 'From', '작업 시작지', '작업 종료지', 'To', '실제 스케줄 시작 시각',
       '실제 스케줄 종료 시각', '작업까지 이동 거리(km)', '작업까지 이동 시간(분)', '작업중 이동 거리(km)',
       '작업중 이동 시간(분)', '도선사', '톤수', '선종', '최종 스케줄 시각', '최초 스케줄 시각', '최초 작업시작지',
       '최초 작업종료지', '최초 예선', '최초 도선사', 'AIS 파일명 target', 'AIS 파일명 tug'],
      dtype='object')

In [ ]:
pd.read_csv("선석 코드.csv")

In [ ]:
pd.read_csv("선석 코드.csv")["선석코드"].unique()

In [ ]:
df = pd.read_csv("2024-06_FristAllSchData.csv")

In [ ]:
df["도선사"].unique()

In [ ]:
pd.read_csv("2024-06_FristAllSchData.csv")

In [ ]:
pd.read_csv("2024-06_SchData.csv")